name: Rust

on:
  push:
  pull_request:
  
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./adder
      run: cargo build --verbose
    - name: Run tests
      working-directory: ./adder
      run: cargo test --verbose
